---
project:
  owner: nich19032@gmail.com
  name: aws-infrastructure-2
  regions:
    - ap-southeast-1

tests:
  test-scenario-1:
    parameters:
      EnvironmentName: Staging
      VpcCIDR: 10.2.0.0/16
    template: ./templates/vpc/vpc.yaml
    s3_bucket: norman-new-infra
    regions:
      - ap-southeast-1
  # test-scenario-2:
  #   parameters:
  #     LatestLinuxAmiId: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  #   template: ./templates/web-service/gettingPublicParameter.yaml
  #   s3_bucket: norman-new-infra
  #   regions:
  #     - ap-southeast-1
