---
project:
  owner: nich19032@gmail.com
  name: aws-infra-2
  regions:
    - ap-southeast-1

tests:
  test-1:
    parameters:
      LatestLinuxAmiId: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
    template: ./templates/web-service/gettingPublicParameter.yaml
    s3_bucket: norman-new-infra
    regions:
      - ap-southeast-1

  test-2:
    parameters:
      EnvironmentName: Staging
      VpcCIDR: 10.2.0.0/16
      PublicSubnet1CIDR: 10.2.32.0/19
      PublicSubnet2CIDR: 10.2.96.0/19
      PublicSubnet3CIDR: 10.2.160.0/19
      PrivateSubnet1CIDR: 10.2.0.0/19
      PrivateSubnet2CIDR: 10.2.64.0/19
      PrivateSubnet3CIDR: 10.2.128.0/19
    template: ./templates/vpc/vpc.yaml
    s3_bucket: norman-new-infra
    regions:
      - ap-southeast-1
