global:
  owner: nich19032@gmail.com
  qsname: aws-infrastructure-2
  regions:
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - us-east-1
  reporting: true
tests:
  test-scenario1:
    parameter_input: input.json
    template_file: temp.yaml
    regions:
      - ap-southeast-1
